/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRecipesImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedCreateRecipeImport } from './routes/_authenticated/create-recipe'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRecipesRoute = AuthenticatedRecipesImport.update({
  path: '/recipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateRecipeRoute = AuthenticatedCreateRecipeImport.update({
  path: '/create-recipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create-recipe': {
      preLoaderRoute: typeof AuthenticatedCreateRecipeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/recipes': {
      preLoaderRoute: typeof AuthenticatedRecipesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedCreateRecipeRoute,
    AuthenticatedRecipesRoute,
    AuthenticatedIndexRoute,
  ]),
  AboutRoute,
])

/* prettier-ignore-end */
